language: python
python:
  - "2.7"
# command to install dependencies

before_install:
  -  wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
  -  tar xvfz ta-lib-0.4.0-src.tar.gz
  -  cd ta-lib
  -  ./configure
  -  make
  -  make install
  -  export PATH=$PATH:$PWD/ta-lib/
  -  export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$PWD/ta-lib/"

install: "pip install -r requirements.txt"
# command to run tests
script: nosetests tests/test_suite.py